import { useState } from 'react';
import { Link } from 'react-router-dom';
import Hambuger from './Hamburger';
import CheckedBox from './Header.module.css';
import Nav from './Nav';
function Header() {
  const [hamburgerOpen, setHamburgerOpen] = useState(false);
  const toggleHambuger = () => {
    return setHamburgerOpen(!hamburgerOpen);
  };
  return (
    <div>
      <head>
        <title>Main page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <header className="fixed inset-x-0 top-0 z-50 left-0 bg-garden3 border-b-2 border-garden4">
        <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <div className="flex items-center mb-4 ">
            <span className="ml-3 text-5xl font-pacifico">
              <Link to="/" className="text-garden1">
                Do Green!
              </Link>
            </span>
          </div>
          <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <div className="mr-5 hover:text-gray-900">
              {/** Rounded switch */}
              <label className={CheckedBox.switch}>
                <input type="checkbox" />
                <span className={`${CheckedBox.slider} ${CheckedBox.round}`} />
              </label>
            </div>
            <div className="mr-5 hover:text-gray-900 ">
              {/** Hambuger Dropdown bar */}
              <button className="bg-garden3" onClick={toggleHambuger}>
                <svg viewBox="0 0 100 80" width="40" height="40" className="fill-garden4">
                  <rect width="100" height="20"></rect>
                  <rect y="30" width="100" height="20"></rect>
                  <rect y="60" width="100" height="20"></rect>
                </svg>
              </button>
            </div>
          </nav>
        </div>
      </header>
      <div className='inset-x-0 top-0 left-0 bg-white p-11'/>
      {hamburgerOpen ? <Hambuger name="Elice" rank="Earth Gardian" /> : null}
  
    </div>
  );
}

export default Header;
